import Head from 'next/head'
import React from 'react'
import Footer from './footer/Footer'
import Navbar from './navbar/Navbar'

const Layout = ({children}) => {
  return (
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

            <Navbar/>
                {children}
            <Footer/>
        </>
  )
}

export default Layout;
